mapping:
  - pattern: ".*dmi.*"
    zone: "NIS"

  - pattern: ".*dms.*"
    zone: "DMZ"

  - pattern: ".*dmn.*"
    zone: "DMZ"

  - pattern: ".*fab.*"
    zone: "Fabric"

  - pattern: ".*gcc.*"
    zone: "NPS"

  - pattern: ".*meb.*"
    zone: "NPS"

  - pattern: ".*oob.*"
    zone: "OOB"
  
  - patter: "^bwp[0-9]{2}.*"
    zone: "BWP"

  