roles:
  admin:
    - read_devices
    - read_accounts
    - create_accounts
    - update_accounts
    - delete_accounts
    - read_logs
    - sync_nagios

  operator:
    - read_devices
    - read_accounts

  user:
    - read_devices
